function handlePromiseError(error) {
    console.error(`Error caught from promise: ${error.message}`);
}


/*
====================================================================================
                            S C R I P T   E X E C U T I O N
====================================================================================
*/

console.log("Entering backgroundHelperFunctions script ...");